version: '3'
services:
  django:
    build: .
    container_name: 'pois_2nd_project'
    working_dir: '/root/'
    # environment: # 環境変数の設定
    tty: true
    volumes:
      - ./app:/root/app
      - ./giraffe:/root/giraffe
      - ./agency:/root/agency
    ports:
      - "8000:8000"
      - "3000:3000"