version: '3'
services:
  django:
    build: .
    container_name: 'pois_2nd_project'
    working_dir: '/root/'
    # environment: # 環境変数の設定
    tty: true
    volumes:
      - ./app:/root/app
    ports:
      - "8000:8000"
  vue:
    build: .
    container_name: 'vue'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./templates:/root/app/templates
    ports:
      - '3000:3000'
