version: '3'
services:
  django:
    build: .
    container_name: 'django'
    working_dir: '/root/'
    # environment: # 環境変数の設定
    tty: true
    volumes:
      - ./../pois-2nd-project/:/root/pois-2nd-project
    ports:
      - "8000:8000"
  vue:
    build: .
    container_name: 'vue'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./../pois-2nd-project/:/root/pois-2nd-project
    ports:
      - '3000:3000'
