# Generated by Django 4.1 on 2023-06-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_dish_remove_menudetail_recipe_id'),
        ('recommend', '0002_remove_recipegraph_id1_recipe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='menudetail',
            name='dish_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipe.dish'),
        ),
    ]
