# Generated by Django 4.1 on 2023-06-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_cookingtool_username_alter_menudetail_dish_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingtool',
            old_name='username',
            new_name='user',
        ),
    ]
