# Generated by Django 4.1 on 2023-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_username_cookingtool_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='menudetail',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='menudetail',
            name='dish_id',
        ),
        migrations.AddField(
            model_name='menudetail',
            name='dish',
            field=models.ManyToManyField(to='recipe.dish'),
        ),
    ]
