# Generated by Django 4.1 on 2023-06-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_rename_username_menu_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudetail',
            name='dish',
        ),
        migrations.AddField(
            model_name='menudetail',
            name='dish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipe.dish'),
        ),
    ]
