# Generated by Django 4.1 on 2023-06-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_selected', models.IntegerField(default=0)),
                ('id1_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeTable1', to='recipe.recipe')),
                ('id2_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeTable2', to='recipe.recipe')),
            ],
        ),
    ]
