# Generated by Django 4.1 on 2023-06-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_dish_remove_menudetail_recipe_id'),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipegraph',
            name='id1_recipe',
        ),
        migrations.RemoveField(
            model_name='recipegraph',
            name='id2_recipe',
        ),
        migrations.AddField(
            model_name='recipegraph',
            name='id1_dish',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='DishTable1', to='recipe.dish'),
        ),
        migrations.AddField(
            model_name='recipegraph',
            name='id2_dish',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='DishTable2', to='recipe.dish'),
        ),
    ]
