# Generated by Django 4.1 on 2023-06-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_remove_recipegraph_id1_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipegraph',
            old_name='id1_dish',
            new_name='dish1',
        ),
        migrations.RenameField(
            model_name='recipegraph',
            old_name='id2_dish',
            new_name='dish2',
        ),
    ]
